version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Adjust if it's in ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lambda_functions
    depends_on:
      - db
    volumes:
      - ./backend:/app  # Optional: for live reload during dev

  db:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lambda_functions
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
